// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace AIBotWithTests1ML.Model
{
    public class ModelInput
    {
        [ColumnName("InPut"), LoadColumn(0)]
        public string InPut { get; set; }


        [ColumnName("OutPut"), LoadColumn(1)]
        public string OutPut { get; set; }


    }
}
