// This file was auto-generated by ML.NET Model Builder. 

using System;
using AIBotWithTests1ML.Model;

namespace AIBotWithTests1ML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                InPut = @"Hello",
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual OutPut with predicted OutPut from sample data...\n\n");
            Console.WriteLine($"InPut: {sampleData.InPut}");
            Console.WriteLine($"\n\nPredicted OutPut value {predictionResult.Prediction} \nPredicted OutPut scores: [{String.Join(",", predictionResult.Score)}]\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
